# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fancyckt.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(591, 485)
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(0, 0, 91, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 40, 537, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(170, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.txt_bat = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txt_bat.setFont(font)
        self.txt_bat.setObjectName("txt_bat")
        self.horizontalLayout.addWidget(self.txt_bat)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.txt_bow = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txt_bow.setFont(font)
        self.txt_bow.setObjectName("txt_bow")
        self.horizontalLayout.addWidget(self.txt_bow)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.txt_ar = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txt_ar.setFont(font)
        self.txt_ar.setObjectName("txt_ar")
        self.horizontalLayout.addWidget(self.txt_ar)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.txt_wk = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txt_wk.setFont(font)
        self.txt_wk.setObjectName("txt_wk")
        self.horizontalLayout.addWidget(self.txt_wk)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(50, 140, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(160, 140, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(410, 140, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(310, 140, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(40, 170, 221, 21))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rdbtn_bat = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.rdbtn_bat.setObjectName("rdbtn_bat")
        self.rdbtn_bat.toggled.connect(self.checkstate)

        self.horizontalLayout_2.addWidget(self.rdbtn_bat)
        self.rdbtn_bow = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.rdbtn_bow.setObjectName("rdbtn_bow")
        self.horizontalLayout_2.addWidget(self.rdbtn_bow)
        self.rdbtn_ar = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.rdbtn_ar.setObjectName("rdbtn_ar")
        self.horizontalLayout_2.addWidget(self.rdbtn_ar)
        self.rdbtn_wk = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.rdbtn_wk.setObjectName("rdbtn_wk")
        self.horizontalLayout_2.addWidget(self.rdbtn_wk)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(310, 170, 201, 21))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_3.addWidget(self.label_15)
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_3.addWidget(self.label_14)

        self.rdbtn_bat.toggled.connect(self.checkstate)
        self.rdbtn_bow.toggled.connect(self.checkstate)
        
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(40, 190, 221, 261))
        self.listWidget.setObjectName("listWidget")
        self.listWidget_2 = QtWidgets.QListWidget(Form)
        self.listWidget_2.setGeometry(QtCore.QRect(310, 190, 201, 261))
        self.listWidget_2.setObjectName("listWidget_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.comboBox.setItemText(0, _translate("Form", "Manage Team"))
        self.comboBox.setItemText(1, _translate("Form", "New Team"))
        self.comboBox.setItemText(2, _translate("Form", "Open Team"))
        self.comboBox.setItemText(3, _translate("Form", "Evalute Team"))
        self.comboBox.setItemText(4, _translate("Form", "Quit"))
        self.label.setText(_translate("Form", "Your Sections"))
        self.label_4.setText(_translate("Form", "Batsmen(BAT)"))
        self.txt_bat.setText(_translate("Form", "4"))
        self.label_3.setText(_translate("Form", "Bowlers(BOW)"))
        self.txt_bow.setText(_translate("Form", "4"))
        self.label_5.setText(_translate("Form", "Allrounders(AR)"))
        self.txt_ar.setText(_translate("Form", "2"))
        self.label_2.setText(_translate("Form", "Wicket-Keeper(WK)"))
        self.txt_wk.setText(_translate("Form", "1"))
        self.label_10.setText(_translate("Form", "Points Avialable "))
        self.label_11.setText(_translate("Form", "100"))
        self.label_12.setText(_translate("Form", "89"))
        self.label_13.setText(_translate("Form", "Points Used"))
        self.rdbtn_bat.setText(_translate("Form", "BAT"))
        self.rdbtn_bow.setText(_translate("Form", "BOW"))
        self.rdbtn_ar.setText(_translate("Form", "AR"))
        self.rdbtn_wk.setText(_translate("Form", "WK"))
        self.label_15.setText(_translate("Form", "Team Name"))
        self.label_14.setText(_translate("Form", "TextLabel"))

    def checkstate(self):
    
       if self.rdbtn_bat.isChecked()==True:
           self.listWidget.setText("Sagen")
       else:
            self.listWidget.setText("null")
       if self.rdbtn_bow.isChecked()==True:
           self.listWidget.setText("Sagen")
       else:
            self.listWidget.setText("null")
       
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

